# Generated by Django 5.1.15 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WitherDutyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dutyDate", models.DateField(verbose_name="值班日")),
                ("shiftName", models.CharField(max_length=40, verbose_name="班次名")),
                (
                    "maxOnDuty",
                    models.PositiveIntegerField(verbose_name="计划在岗槽数上限"),
                ),
                (
                    "supervisor",
                    models.CharField(max_length=60, verbose_name="值班主管名"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_cards",
                        to="gardens.garden",
                        verbose_name="茶园",
                    ),
                ),
            ],
            options={
                "verbose_name": "萎凋值班卡",
                "verbose_name_plural": "萎凋值班卡",
                "ordering": ["-dutyDate", "garden__name", "shiftName"],
            },
        ),
        migrations.AddConstraint(
            model_name="witherdutycard",
            constraint=models.UniqueConstraint(
                fields=("garden", "dutyDate", "shiftName"),
                name="uniq_duty_card_per_garden_date_shift",
            ),
        ),
    ]
